apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEV3TURFdwpPVE13TURCYUZ3MDBNVEV3TURFd09UTXdNREJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFESENxNU8xcUpma29OeXM3Sms3Rit3SFJPdzBzcHdHT2VpZXMyRXFYYnFVRHFiZFFvTQo5S0c5WlpMK2xFc0l1SkNFaTM2RTl5THZkSmh3ZUNtVS9WS1F3RzdFdy9zQ0FxQjV5WjdnNERTZFFIN2UyeVdQCnF2ZkQvMCtoeE1CYTdxTTVuVVhkRVZZWkJ0bDFxTGNzbkhHSkpRTFNQTENaTkNJMzZjY1RQRHVqUzlCS3FnaWgKR3RzV1AzRkpSWTNtQkZXekkvRGt1WXlpNmt5b3NoL3p1VXNjaW03QTRKVjZHVStMeGlCTExIS3RHUmFLc0FzaApRejBTS2hhN3N3Q3pNYkNIRGREWG1hbW9oY1ZYTzBxOExBa0psYW9iVmFLTDlieWJQcS90YS9vclZnUndNL1ZRClpLbXlYSXpaYTJaR292VnVqbUY5OWEyYWpUY1UvZThaL1FCZkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNaeEpFZ1JZVENIcE8rVUNUWApDUTVjY1FKaTBEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFJTS93eW14Qyt3R0FtaGtFSUt0RjJwUkZRdlRvCms4S1d5bjFHcXU5YzI1TTFXWklTMWlHL2RKcGJhV3Q5MVBuMTRDUDNkV2VGZHJuNGlpd1J3cHZKM2lrSjA0blgKd2t1OTF5L21sMXVaOXBEa3JsVE5EaHZEbnk1MWN6Z0UxSlgzVC9SeTBkc0lwL3JYR3JtVEZEZW1FNnY1WmtRcwpEa1F5RWMwcjkyVC91TVlWckpqVVV2WWRXazBiUEdiM082R3pETWVqODZmRk14N3ozajEzV2c2NHd6Y2x5SWVLCmR6a25QKzRDUmNmRVBvU2RydFV0M204SlJPYzlxZ29kMWg2QTlGeTVQUUdzc3lrcjh5WXVDdmo3bjdPWWU5Y2cKVmVvZlIxdHlDL0Z4S3JpUFZOby8zamgzaWFJenpaN01GbUpoQ1Q1TE9BVnZJNnVja0FnUXcvTWk3dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://6f478933-c043-485c-8467-8646dad3edeb.k8s.ondigitalocean.com
  name: do-sgp1-k8s-do
contexts:
- context:
    cluster: do-sgp1-k8s-do
    user: do-sgp1-k8s-do-admin
  name: do-sgp1-k8s-do
current-context: do-sgp1-k8s-do
kind: Config
preferences: {}
users:
- name: do-sgp1-k8s-do-admin
  user:
    token: d9449c61f97a6f7c8132a1479d10f0e76abf1a3362e1a0a9f0fc393fa662e1bf
